#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
clear
cat welcome
echo "_______KERNEL:"
uname -a
cat << EOF

       [ENTER] <- START_EMBEDDED_APPLICATION
       [c] <- COMMAND_PROMPT
EOF
read -p "_______CHOOSE:" input

case $input in
  c) /bin/sh ;;
  *) /bin/sh /app/init ;;
esac
