#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
clear
cat welcome
echo "_______KERNEL"
uname -a
cat << EOF



_______PRESS [ENTER] FOR DISK NOMAD OR [C] FOR COMMAND PROMPT
EOF
read -p "_______CHOOSE:" input

case $input in
  c) /bin/sh ;;
  *) /bin/sh /home/main ;;
esac
